# We need to override distribution ansible variables 
# to make it work with PopOS

remi_repo_url: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
os_installed_packages:
  - code
  - google-chrome-stable
  - flameshot
  - jq
  - htop
  - zsh
  - bat
  - wget 
  - git
  - golang
  - direnv
  - yadm
  - neovim
  - filezilla
  # gnome
  - gnome-tweaks 

flatpack_installed_packages:
  - https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
  - https://dl.flathub.org/repo/appstream/us.zoom.Zoom.flatpakref
  - https://dl.flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
  - https://dl.flathub.org/repo/appstream/com.slack.Slack.flatpakref
  - https://dl.flathub.org/repo/appstream/com.getpostman.Postman.flatpakref
  - https://dl.flathub.org/repo/appstream/com.bitwarden.desktop.flatpakref
  - https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
  - https://dl.flathub.org/repo/appstream/org.videolan.VLC.flatpakref
  - https://dl.flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref
  - https://dl.flathub.org/repo/appstream/org.gnome.meld.flatpakref
  # gnome
  - https://dl.flathub.org/repo/appstream/org.gnome.Extensions.flatpakref
