---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - default.config.yml

  tasks:
    - include_tasks: tasks/setup.yml
      tags: ['setup']

    - include_tasks: tasks/terraform.yml
      tags: ['setup']

    - include_tasks: tasks/circleci-cli.yml
      tags: ['setup']

    - include_tasks: tasks/gcloud.yml
      tags: ['setup']

    - include_tasks: tasks/lando.yml
      tags: ['setup']
    
    - include_tasks: tasks/flatpak.yml
      tags: ['flatpak']  

    - include_tasks: tasks/sudoers.yml
      tags: ['setup']  
  

  roles:
    - role: geerlingguy.docker
      tags: ['docker']
    - role: geerlingguy.php-versions
      tags: ['php']
    - role: geerlingguy.php
      tags: ['php']
    - role: geerlingguy.composer
      tags: ['php']
    - role: stephdewit.nvm
      tags: ['node']
      become: yes
      become_user: omers
      environment:
        NVM_DIR: /home/omers/.nvm
        