---
- hosts: localhost
  become: true

  pre_tasks:
  #   - name: update repositories
  #     apt: update_cache=yes
  #     changed_when: False
  # - name: Set the stable docker repository
  #   apt_repository: 
  #     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
  #     state: present
  #     update_cache: yes 

  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - google-chrome-stable
      - jq
      - zsh
  

  roles:
    - role: geerlingguy.docker
      docker_install_compose: true
      docker_package: "docker-ce=19.03.9"
    - role: stephdewit.nvm
      become: yes
      become_user: omers
      environment:
        NVM_DIR: /home/omers/.nvm
    
    