collections:
  - name: community.general
roles:
  
  - name: geerlingguy.repo-remi
  - name: geerlingguy.docker
  - name: geerlingguy.php-versions
  - name: geerlingguy.php
  - name: geerlingguy.composer
  - name: stephdewit.nvm
  - name: hurricanehrndz.rustup
