- name: Install flatpack packages
  flatpak: name={{item}} state=present
  with_items:
    - https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    - https://dl.flathub.org/repo/appstream/us.zoom.Zoom.flatpakref
    - https://dl.flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
    - https://dl.flathub.org/repo/appstream/org.gnome.meld.flatpakref
    - https://dl.flathub.org/repo/appstream/com.slack.Slack.flatpakref
    - https://dl.flathub.org/repo/appstream/com.getpostman.Postman.flatpakref