- name: Set google cloud sdk repo 
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK repo 
    file: google-cloud-sdk
    gpgkey: |
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64

- name: Installing os packages
  dnf:
    pkg: 
      - google-cloud-sdk
      - kubectl
    state: latest