- name: Clone kubectx
  git:  
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx


- name: Create symbolic link (kubectx)
  file:
    src: /opt/kubectx/kubectx
    dest: /usr/local/bin/kubectx
    state: link

- name: Create symbolic link (kubens)
  file:
    src: /opt/kubectx/kubens
    dest: /usr/local/bin/kubens
    state: link

- name: Get assets lens IDE
  get_url:
    url: "https://api.github.com/repos/lensapp/lens/releases/latest?access_token={{ github_token }}"
    force: yes
    headers:
      Accept: "application/vnd.github.v3+json"
    dest: "/tmp/lens.json"

- name: Get download url
  shell: |
    cat "/tmp/lens.json" | jq '.assets | .[] | select(.browser_download_url | contains("amd64.deb")) | .url' | sed -e 's/^"//' -e 's/"$//'
  register: "download_url"

- debug:
    msg: "{{ download_url.stdout }}"

- name: Download latest release
  get_url:
    url: "{{ download_url.stdout }}?access_token={{ github_token }}"
    dest: /tmp/lens.deb
    tmp_dest: /tmp/
    force: yes
    headers:
      Accept: "application/octet-stream"

- name: Install a .deb package
  apt:
    deb: /tmp/lens.deb