---
- name: Set microsoft repo for vs code
  yum_repository:
    name: code
    description: vscode
    file: vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    baseurl: https://packages.microsoft.com/yumrepos/vscode

- name: Set repo for yadm (via command)
  command:
    # cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_Rawhide/home:TheLocehiliosan:yadm.repo
    cmd: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_33/home:TheLocehiliosan:yadm.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/yadm.repo

- name: Installing os packages
  dnf:
    pkg: "{{os_installed_packages}}"
    state: latest


- name: Installing flatpak packages
  flatpak:
    name: "{{item}}"
    state: present
  with_items: "{{flatpack_installed_packages}}"

- name: Ensure that font directory exist
  file:
    path: /usr/share/fonts
    state: directory

- name: Download and unarchive fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: /usr/share/fonts
    remote_src: yes

- name: Download and unarchive fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraMono.zip
    dest: /usr/share/fonts
    remote_src: yes

- name: Installing starship prompt
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- -y
  args:
    warn: no

- name: Installing CircleCI cli
  shell: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
  args:
    warn: no

- name: Installing Lando
  dnf:
    name: https://files.devwithlando.io/lando-stable.rpm
    state: present
    disable_gpg_check: true
