- name: Installing os packages
  apt:
    pkg: "{{apt_installed_packages}}"
    state: present

- name: Installing flatpak packages
  community.general.flatpak:
    name: "{{item}}"
    state: present
  with_items: "{{flatpack_installed_packages}}"

- name: Download and unarchive fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: /usr/local/share/fonts
    remote_src: yes

- name: Download and unarchive fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraMono.zip
    dest: /usr/local/share/fonts
    remote_src: yes

- name: Installing starship prompt
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- -y
  args:
    warn: no

- name: Installing CircleCI cli
  shell: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
  args:
    warn: no

- name: Installing Lando
  apt:
    deb: https://files.devwithlando.io/lando-stable.deb