- name: Add an apt key terraform
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add repository Terraform
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: Install terraform
  apt:
    pkg: terraform
    state: present
    update_cache: true