- name: Set repo for hashicorp (via command)
  command:
    cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    warn: false
  args:
    creates: /etc/yum.repos.d/hashicorp.repo

- name: install a modularity appstream with defined profile
  dnf:
    name: 
      - terraform
      - vagrant
    state: latest
