- name: Install packages required for yubikey
  dnf:
    pkg:
      - gnupg2
      - yubikey-manager
      - pcsc-lite 
      - pinentry-tty
    state: latest

# Fix the need to reboot pcscd each time we login (use it if you used your yubi just for gpg)
# https://bugzilla.redhat.com/show_bug.cgi?id=1893131
- name: Uninstall opensc for yubikey
  dnf:
    pkg:
      - opensc
    state: absent
