- name: Add repository yubico
  apt_repository:
    repo: ppa:yubico/stable

- name: Install packages required for yubikey
  apt:
    pkg: 
      - gnupg
      - yubikey-manager
      - scdaemon
      - pcscd
      - pinentry-tty
    state: present